/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Diaglog: typeof import('./src/components/Base/Diaglog.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    LoanCalulator: typeof import('./src/components/LoanCalulator.vue')['default']
    MicTable: typeof import('./src/components/MicTable.vue')['default']
    ReadXlsx: typeof import('./src/components/ReadXlsx.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TodoItem: typeof import('./src/components/TodoItem.vue')['default']
    TodoList: typeof import('./src/components/TodoList.vue')['default']
  }
}
