version: "3.8"

services:
  frontend:
    image: vite-image
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: yarn dev --host --port 8080

